[package]
name = "pomodorust"
version = "0.1.0"
# FIX: Changed edition to 2021 for stability.
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = { version = "0.29.0", features = ["all-widgets"] }
crossterm = "0.29.0"
chrono = "0.4.41"
rodio = "0.20.1"
serde = { version = "1.0.219", features = ["derive"] }
directories = "6.0.0"
serde_json = "1.0.140"
notify-rust = "4.11.7"