name: Build

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: full
  RUST_LOG: info
  RUSTFLAGS: "-C link-arg=-s"

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET:
          # - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
          # - x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Install ALSA development libraries
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev
      - name: Install Rust target ${{ matrix.BUILD_TARGET }}
        run: rustup target add ${{ matrix.BUILD_TARGET }}
      - name: Build binaries for ${{ matrix.BUILD_TARGET }}
        run: cargo build --release --target ${{ matrix.BUILD_TARGET }}
      - name: Run tests for ${{ matrix.BUILD_TARGET }}
        run: cargo test --release --target ${{ matrix.BUILD_TARGET }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: pomodorust-${{ matrix.BUILD_TARGET }}
          path: target/${{ matrix.BUILD_TARGET }}/release/pomodorust
      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        BUILD_TARGET:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Install Homebrew dependencies
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install alsa-lib
      - name: Install Rust target ${{ matrix.BUILD_TARGET }}
        run: rustup target add ${{ matrix.BUILD_TARGET }}
      - name: Build binaries for ${{ matrix.BUILD_TARGET }}
        run: cargo build --release --target ${{ matrix.BUILD_TARGET }}
      - name: Run tests for ${{ matrix.BUILD_TARGET }}
        run: cargo test --release --target ${{ matrix.BUILD_TARGET }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: pomodorust-${{ matrix.BUILD_TARGET }}
          path: target/${{ matrix.BUILD_TARGET }}/release/pomodorust
      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
